[package]
name = "users"
description = "Library for getting information on Unix users and groups"

authors = [ "ogham@bsago.me" ]
documentation = "http://ogham.rustdocs.org/users/"
homepage = "https://github.com/ogham/rust-users"
license = "MIT"
readme = "README.md"
version = "0.5.0"

[dependencies]
libc = "0.2"
