[package]

name = "users"
description = "Library for getting information on Unix users and groups"

authors = [ "ogham@bsago.me" ]
documentation = "http://bsago.me/doc/users/"
homepage = "https://github.com/ogham/rust-users"
license = "MIT"
readme = "README.md"
version = "0.2.3"

[dependencies]
libc = "0.1.1"